CAEN_SLEEP_AFTER_TCP = 0.250
FNAL_SLEEP_AFTER_TCP = 0.250
JULA_SLEEP_AFTER_TCP = 0.250

CTRLTABLE_LV_NAME_COL = 0
CTRLTABLE_LV_STAT_COL= 1
CTRLTABLE_LV_VSET_COL= 2
CTRLTABLE_LV_VREAD_COL = 3
CTRLTABLE_LV_CURR_COL = 4
CTRLTABLE_HV_NAME_COL = 5
CTRLTABLE_HV_STAT_COL= 6
CTRLTABLE_HV_VSET_COL= 7
CTRLTABLE_HV_VREAD_COL = 8
CTRLTABLE_HV_CURR_COL = 9
CTRLTABLE_FC7ID_COL = 10
CTRLTABLE_FC7SLOT_COL = 11

MIN_LV = 0
MAX_LV = 12
MIN_HV = 0
MAX_HV = 400
HV_ON_THR = 20


BI_TEMP_TOLERANCE = 2
BI_SLEEP_AFTER_LVSET = 30
BI_SLEEP_AFTER_HVSET = 60
BI_SLEEP_AFTER_TEMP_CHECK = 5
BI_ACTION_RETRIES = 20
BI_ACTION_RETRY_SLEEP = 10
TEST_PROCESS_SLEEP = 5
BI_HIGHFLOW_THRESHOLD = -50

NUM_BI_SLOTS = 10

MONITOR_UPDATE_LIMIT = 60
MONITOR_SLEEP = 3
MAX_VALID_TEMP = 900.0

SUPERVISOR_START_DELAY = 60
SUPERVISOR_SLEEP = 30
TEMP_WARNING = 38
TEMP_ERROR = 40

FNAL_T0_OFFSET = 0
FNAL_T1_OFFSET = 1
FNAL_RS_OFFSET = 2
FNAL_OW_OFFSET = 4
FNAL_DP_OFFSET = 14
FNAL_RS_THR = 100.0

