Julabo:
 Addr: "192.168.0.2"
 Port: "5050"
 EnableMonitor: "True"
MQTT:
 Addr: "192.168.0.45"
 Port: "1883"
 CAENTopic: "/caenstatus/full"
 M5Topic: "/environment/HumAndTemp001"
 EnableMonitor: "True"
FNALBox:
 Addr: "192.168.0.187"
 Port: "10001"
 EnableMonitor: "True"
CAENController:
 Addr: "192.168.0.45"
 Port: "7000"
DB:
 Addr: "192.168.0.45"
 Port: "5000"
Supervisor:
 Enabled: "True"
BITest:
 cwd: "/home/thermal/BurnIn_moduleTest_v4-22"
 
